// src/utils/stopwords-es.js
export const STOPWORDS_ES = new Set([
    "a",
    "acá",
    "ahí",
    "al",
    "algo",
    "algún",
    "alguna",
    "algunas",
    "algunos",
    "allí",
    "allá",
    "ante",
    "antes",
    "aquel",
    "aquella",
    "aquello",
    "aquellas",
    "aquellos",
    "aquí",
    "así",
    "cada",
    "como",
    "con",
    "contra",
    "cual",
    "cuales",
    "cualquier",
    "cualesquiera",
    "cuan",
    "cuando",
    "cuanto",
    "cuantos",
    "cuánta",
    "cuántas",
    "cuánto",
    "cuántos",
    "de",
    "del",
    "desde",
    "donde",
    "el",
    "ella",
    "ellas",
    "ello",
    "ellos",
    "en",
    "entre",
    "era",
    "erais",
    "eran",
    "eras",
    "eres",
    "es",
    "esa",
    "esas",
    "ese",
    "eso",
    "esos",
    "esta",
    "estaban",
    "estado",
    "estamos",
    "estar",
    "estas",
    "este",
    "esto",
    "estos",
    "fue",
    "fueron",
    "fui",
    "ha",
    "había",
    "habían",
    "haber",
    "habrá",
    "habrán",
    "hace",
    "hacen",
    "hacer",
    "hacia",
    "han",
    "hasta",
    "hay",
    "la",
    "las",
    "le",
    "les",
    "lo",
    "los",
    "mas",
    "más",
    "me",
    "mi",
    "mis",
    "mientras",
    "muy",
    "nada",
    "ni",
    "no",
    "nos",
    "nosotros",
    "nuestra",
    "nuestras",
    "nuestro",
    "nuestros",
    "o",
    "os",
    "otra",
    "otras",
    "otro",
    "otros",
    "para",
    "pero",
    "poco",
    "por",
    "porque",
    "que",
    "se",
    "sea",
    "según",
    "ser",
    "si",
    "sí",
    "sin",
    "sobre",
    "su",
    "sus",
    "tal",
    "también",
    "tan",
    "tanto",
    "te",
    "tenía",
    "tenían",
    "tener",
    "ti",
    "tiene",
    "tienen",
    "toda",
    "todas",
    "todo",
    "todos",
    "tu",
    "tus",
    "un",
    "una",
    "uno",
    "unos",
    "usted",
    "vos",
    "ya",
    "y",
    "e",
    "u",
]);

/*
 El archivo stopwords-es.js es una lista de palabras comunes en español que tu buscador ignora para no generar resultados irrelevantes.
 Se usa como filtro previo antes de comparar lo que escribe el usuario con los artículos y su contenido.

 Ejemplo:
 Frase: "empezar el proceso"
 Tokens: ["empezar", "el", "proceso"]
 Filtrado (stopwords y cortas): ["empezar", "proceso"]

 el” se elimina porque está en STOPWORDS_ES.
 Así evitas coincidencias falsas como marcar "el" dentro de "elementos".

  Beneficios:

    Menos ruido: no devuelve resultados por coincidencias en palabras irrelevantes.
    Más precisión: enfoca la búsqueda en los términos importantes.
    Consistencia: siempre se ignoran las mismas palabras en cualquier búsqueda.

 */
